# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TonyPls' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    # React Native requirements
    rn_path = '../node_modules/react-native'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'DevSupport'
  
    ]

  # Pods for TonyPls

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  # pod 'Firebase/Invites', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  #pod 'Firebase/RemoteConfig', '~> 5.11.0'
  #pod 'Firebase/Storage', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'GoogleAppMeasurement', '5.3'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

ENV["COCOAPODS_DISABLE_STATS"] = "true"